#Step-1
FROM node:20-alpine AS builder
WORKDIR /app
COPY ./package*.json ./
RUN apk update && apk upgrade && npm install
COPY ./ ./
RUN chmod +x node_modules/.bin/vite
RUN npm run build

#Step-2
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

