apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/deepanshu1894/argo-repo-backend:78ff9b1e9e443c8ef1fcc35d171d1473fc908fc9@sha256:1a91f172b703821d18c2956fe5ddcb10799ca0e837f660942d85bfd9f5f1fe6c
        env:
          - name: MONGODB_URI
            value: mongodb+srv://piyush133jain:jobportal@cluster0.psiszei.mongodb.net
          - name: CLOUD_NAME
            value: drc4x0jax
          - name: API_KEY
            value: "462718162439316"
          - name: API_SECRET
            value: vLwn0Ncryq0SpEwKs6JalIuOqBI
          - name: PORT
            value: "5000"
          - name: SECRET_KEY
            value: dev#piyush
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
