apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/deepanshu1894/argo-repo-frontend:73795f59780614e8829591817c4f4bd0e93a5418@sha256:5de08fb99f5492bb5e9b74a6b32afd4217ef134d4f99c0b8ece01fc2358efd41

        env:
          - name: MONGODB_URI
            value: mongodb+srv://piyush133jain:jobportal@cluster0.psiszei.mongodb.net
          - name: CLOUD_NAME
            value: drc4x0jax
          - name: API_KEY
            value: "462718162439316"
          - name: API_SECRET
            value: vLwn0Ncryq0SpEwKs6JalIuOqBI
          - name: PORT
            value: "5000"
          - name: SECRET_KEY
            value: dev#piyush
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
