apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/deepanshu1894/argo-repo-backend:d5f608e60ce2b839215b4363a6ff0dfe4efbd8c5
        platform: linux/amd64
        env:
          - name: MONGODB_URI
            value: mongodb+srv://piyush133jain:jobportal@cluster0.psiszei.mongodb.net
          - name: CLOUD_NAME
            value: drc4x0jax
          - name: API_KEY
            value: "462718162439316"
          - name: API_SECRET
            value: vLwn0Ncryq0SpEwKs6JalIuOqBI
          - name: PORT
            value: "5000"
          - name: SECRET_KEY
            value: dev#piyush
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
