apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/deepanshu1894/argo-repo-frontend:1d16c3259cd04b7ea955263138420e903c7a56e6@sha256:e170c436d2ef3cf0efb6edee3e0569de94c796ec446becb163b1c8c4d519d12c
        ports:
        - containerPort: 80 # adjust if needed
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
