name: Build & Push Docker Image

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'
    branches:
      - main  # or your default branch

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        if: contains(github.event.head_commit.message, 'backend') || contains(github.event.commits.*.modified, 'backend/')
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository }}-backend:${{ github.sha }}

      - name: Build and push frontend image
        if: contains(github.event.head_commit.message, 'frontend') || contains(github.event.commits.*.modified, 'frontend/')
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository }}-frontend:${{ github.sha }}
